server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location ~ ^(.+)/+$ {
    return 301 $scheme://$http_host$1$is_args$args;
  }

  location / {
    try_files $uri $uri/index.html $uri.html =404;
  }

  error_page 404 /404.html;

  location = /404.html {
    internal;
  }
}
