name: publish
on:
  push:
    branches: [main]
    tags: ["*"]

permissions:
  contents: read
  packages: write

jobs:
  build-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build and export
        env:
          NEXT_TELEMETRY_DISABLED: '1'
        run: |
          npm run build

      - name: Upload static export
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: out

  build-and-push:
    needs: build-static
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download static export
        uses: actions/download-artifact@v4
        with:
          name: out
          path: out

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to GHCR
        uses: docker/build-push-action@v6
        with:
          context: out
          file: Dockerfile
          push: true
          platforms: linux/arm64,linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Coolify
        run: |
          set -e
          curl --fail --show-error \
            --request GET "${{ secrets.COOLIFY_WEBHOOK }}" \
            --header "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}"
